// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/document.proto

package document

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessPdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfBytes      []byte                 `protobuf:"bytes,1,opt,name=pdf_bytes,json=pdfBytes,proto3" json:"pdf_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPdfRequest) Reset() {
	*x = ProcessPdfRequest{}
	mi := &file_proto_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPdfRequest) ProtoMessage() {}

func (x *ProcessPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPdfRequest.ProtoReflect.Descriptor instead.
func (*ProcessPdfRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPdfRequest) GetPdfBytes() []byte {
	if x != nil {
		return x.PdfBytes
	}
	return nil
}

type ProcessPdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfId         string                 `protobuf:"bytes,1,opt,name=pdf_id,json=pdfId,proto3" json:"pdf_id,omitempty"`
	Values        map[string]string      `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegistryJson  string                 `protobuf:"bytes,3,opt,name=registry_json,json=registryJson,proto3" json:"registry_json,omitempty"` // Serialized JSON containing pages, fields, and word anchors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPdfResponse) Reset() {
	*x = ProcessPdfResponse{}
	mi := &file_proto_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPdfResponse) ProtoMessage() {}

func (x *ProcessPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPdfResponse.ProtoReflect.Descriptor instead.
func (*ProcessPdfResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPdfResponse) GetPdfId() string {
	if x != nil {
		return x.PdfId
	}
	return ""
}

func (x *ProcessPdfResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ProcessPdfResponse) GetRegistryJson() string {
	if x != nil {
		return x.RegistryJson
	}
	return ""
}

type GeneratePdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfBytes      []byte                 `protobuf:"bytes,1,opt,name=pdf_bytes,json=pdfBytes,proto3" json:"pdf_bytes,omitempty"`
	FormData      map[string]string      `protobuf:"bytes,2,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePdfRequest) Reset() {
	*x = GeneratePdfRequest{}
	mi := &file_proto_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePdfRequest) ProtoMessage() {}

func (x *GeneratePdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePdfRequest.ProtoReflect.Descriptor instead.
func (*GeneratePdfRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratePdfRequest) GetPdfBytes() []byte {
	if x != nil {
		return x.PdfBytes
	}
	return nil
}

func (x *GeneratePdfRequest) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

type GeneratePdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfBytes      []byte                 `protobuf:"bytes,1,opt,name=pdf_bytes,json=pdfBytes,proto3" json:"pdf_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePdfResponse) Reset() {
	*x = GeneratePdfResponse{}
	mi := &file_proto_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePdfResponse) ProtoMessage() {}

func (x *GeneratePdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePdfResponse.ProtoReflect.Descriptor instead.
func (*GeneratePdfResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{3}
}

func (x *GeneratePdfResponse) GetPdfBytes() []byte {
	if x != nil {
		return x.PdfBytes
	}
	return nil
}

type GenerateDocxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocxBytes     []byte                 `protobuf:"bytes,1,opt,name=docx_bytes,json=docxBytes,proto3" json:"docx_bytes,omitempty"`
	FormData      map[string]string      `protobuf:"bytes,2,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDocxRequest) Reset() {
	*x = GenerateDocxRequest{}
	mi := &file_proto_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDocxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocxRequest) ProtoMessage() {}

func (x *GenerateDocxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocxRequest.ProtoReflect.Descriptor instead.
func (*GenerateDocxRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateDocxRequest) GetDocxBytes() []byte {
	if x != nil {
		return x.DocxBytes
	}
	return nil
}

func (x *GenerateDocxRequest) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

type GenerateDocxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocxBytes     []byte                 `protobuf:"bytes,1,opt,name=docx_bytes,json=docxBytes,proto3" json:"docx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDocxResponse) Reset() {
	*x = GenerateDocxResponse{}
	mi := &file_proto_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDocxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocxResponse) ProtoMessage() {}

func (x *GenerateDocxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocxResponse.ProtoReflect.Descriptor instead.
func (*GenerateDocxResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateDocxResponse) GetDocxBytes() []byte {
	if x != nil {
		return x.DocxBytes
	}
	return nil
}

type StampSignatureRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PdfBytes            []byte                 `protobuf:"bytes,1,opt,name=pdf_bytes,json=pdfBytes,proto3" json:"pdf_bytes,omitempty"`
	SignatureImageBytes []byte                 `protobuf:"bytes,2,opt,name=signature_image_bytes,json=signatureImageBytes,proto3" json:"signature_image_bytes,omitempty"`
	PdfId               string                 `protobuf:"bytes,3,opt,name=pdf_id,json=pdfId,proto3" json:"pdf_id,omitempty"`
	RegistryJson        string                 `protobuf:"bytes,4,opt,name=registry_json,json=registryJson,proto3" json:"registry_json,omitempty"`               // Serialized structural metadata of the PDF
	CacheMappingJson    string                 `protobuf:"bytes,5,opt,name=cache_mapping_json,json=cacheMappingJson,proto3" json:"cache_mapping_json,omitempty"` // Serialized field mapping configuration
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StampSignatureRequest) Reset() {
	*x = StampSignatureRequest{}
	mi := &file_proto_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StampSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampSignatureRequest) ProtoMessage() {}

func (x *StampSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampSignatureRequest.ProtoReflect.Descriptor instead.
func (*StampSignatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{6}
}

func (x *StampSignatureRequest) GetPdfBytes() []byte {
	if x != nil {
		return x.PdfBytes
	}
	return nil
}

func (x *StampSignatureRequest) GetSignatureImageBytes() []byte {
	if x != nil {
		return x.SignatureImageBytes
	}
	return nil
}

func (x *StampSignatureRequest) GetPdfId() string {
	if x != nil {
		return x.PdfId
	}
	return ""
}

func (x *StampSignatureRequest) GetRegistryJson() string {
	if x != nil {
		return x.RegistryJson
	}
	return ""
}

func (x *StampSignatureRequest) GetCacheMappingJson() string {
	if x != nil {
		return x.CacheMappingJson
	}
	return ""
}

type StampSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfBytes      []byte                 `protobuf:"bytes,1,opt,name=pdf_bytes,json=pdfBytes,proto3" json:"pdf_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StampSignatureResponse) Reset() {
	*x = StampSignatureResponse{}
	mi := &file_proto_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StampSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampSignatureResponse) ProtoMessage() {}

func (x *StampSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampSignatureResponse.ProtoReflect.Descriptor instead.
func (*StampSignatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{7}
}

func (x *StampSignatureResponse) GetPdfBytes() []byte {
	if x != nil {
		return x.PdfBytes
	}
	return nil
}

var File_proto_document_proto protoreflect.FileDescriptor

const file_proto_document_proto_rawDesc = "" +
	"\n" +
	"\x14proto/document.proto\x12\bdocument\"0\n" +
	"\x11ProcessPdfRequest\x12\x1b\n" +
	"\tpdf_bytes\x18\x01 \x01(\fR\bpdfBytes\"\xcd\x01\n" +
	"\x12ProcessPdfResponse\x12\x15\n" +
	"\x06pdf_id\x18\x01 \x01(\tR\x05pdfId\x12@\n" +
	"\x06values\x18\x02 \x03(\v2(.document.ProcessPdfResponse.ValuesEntryR\x06values\x12#\n" +
	"\rregistry_json\x18\x03 \x01(\tR\fregistryJson\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x12GeneratePdfRequest\x12\x1b\n" +
	"\tpdf_bytes\x18\x01 \x01(\fR\bpdfBytes\x12G\n" +
	"\tform_data\x18\x02 \x03(\v2*.document.GeneratePdfRequest.FormDataEntryR\bformData\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x13GeneratePdfResponse\x12\x1b\n" +
	"\tpdf_bytes\x18\x01 \x01(\fR\bpdfBytes\"\xbb\x01\n" +
	"\x13GenerateDocxRequest\x12\x1d\n" +
	"\n" +
	"docx_bytes\x18\x01 \x01(\fR\tdocxBytes\x12H\n" +
	"\tform_data\x18\x02 \x03(\v2+.document.GenerateDocxRequest.FormDataEntryR\bformData\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14GenerateDocxResponse\x12\x1d\n" +
	"\n" +
	"docx_bytes\x18\x01 \x01(\fR\tdocxBytes\"\xd2\x01\n" +
	"\x15StampSignatureRequest\x12\x1b\n" +
	"\tpdf_bytes\x18\x01 \x01(\fR\bpdfBytes\x122\n" +
	"\x15signature_image_bytes\x18\x02 \x01(\fR\x13signatureImageBytes\x12\x15\n" +
	"\x06pdf_id\x18\x03 \x01(\tR\x05pdfId\x12#\n" +
	"\rregistry_json\x18\x04 \x01(\tR\fregistryJson\x12,\n" +
	"\x12cache_mapping_json\x18\x05 \x01(\tR\x10cacheMappingJson\"5\n" +
	"\x16StampSignatureResponse\x12\x1b\n" +
	"\tpdf_bytes\x18\x01 \x01(\fR\bpdfBytes2\xca\x02\n" +
	"\x0fDocumentService\x12G\n" +
	"\n" +
	"ProcessPdf\x12\x1b.document.ProcessPdfRequest\x1a\x1c.document.ProcessPdfResponse\x12J\n" +
	"\vGeneratePdf\x12\x1c.document.GeneratePdfRequest\x1a\x1d.document.GeneratePdfResponse\x12M\n" +
	"\fGenerateDocx\x12\x1d.document.GenerateDocxRequest\x1a\x1e.document.GenerateDocxResponse\x12S\n" +
	"\x0eStampSignature\x12\x1f.document.StampSignatureRequest\x1a .document.StampSignatureResponseB!Z\x1fgateway/proto/document;documentb\x06proto3"

var (
	file_proto_document_proto_rawDescOnce sync.Once
	file_proto_document_proto_rawDescData []byte
)

func file_proto_document_proto_rawDescGZIP() []byte {
	file_proto_document_proto_rawDescOnce.Do(func() {
		file_proto_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_document_proto_rawDesc), len(file_proto_document_proto_rawDesc)))
	})
	return file_proto_document_proto_rawDescData
}

var file_proto_document_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_document_proto_goTypes = []any{
	(*ProcessPdfRequest)(nil),      // 0: document.ProcessPdfRequest
	(*ProcessPdfResponse)(nil),     // 1: document.ProcessPdfResponse
	(*GeneratePdfRequest)(nil),     // 2: document.GeneratePdfRequest
	(*GeneratePdfResponse)(nil),    // 3: document.GeneratePdfResponse
	(*GenerateDocxRequest)(nil),    // 4: document.GenerateDocxRequest
	(*GenerateDocxResponse)(nil),   // 5: document.GenerateDocxResponse
	(*StampSignatureRequest)(nil),  // 6: document.StampSignatureRequest
	(*StampSignatureResponse)(nil), // 7: document.StampSignatureResponse
	nil,                            // 8: document.ProcessPdfResponse.ValuesEntry
	nil,                            // 9: document.GeneratePdfRequest.FormDataEntry
	nil,                            // 10: document.GenerateDocxRequest.FormDataEntry
}
var file_proto_document_proto_depIdxs = []int32{
	8,  // 0: document.ProcessPdfResponse.values:type_name -> document.ProcessPdfResponse.ValuesEntry
	9,  // 1: document.GeneratePdfRequest.form_data:type_name -> document.GeneratePdfRequest.FormDataEntry
	10, // 2: document.GenerateDocxRequest.form_data:type_name -> document.GenerateDocxRequest.FormDataEntry
	0,  // 3: document.DocumentService.ProcessPdf:input_type -> document.ProcessPdfRequest
	2,  // 4: document.DocumentService.GeneratePdf:input_type -> document.GeneratePdfRequest
	4,  // 5: document.DocumentService.GenerateDocx:input_type -> document.GenerateDocxRequest
	6,  // 6: document.DocumentService.StampSignature:input_type -> document.StampSignatureRequest
	1,  // 7: document.DocumentService.ProcessPdf:output_type -> document.ProcessPdfResponse
	3,  // 8: document.DocumentService.GeneratePdf:output_type -> document.GeneratePdfResponse
	5,  // 9: document.DocumentService.GenerateDocx:output_type -> document.GenerateDocxResponse
	7,  // 10: document.DocumentService.StampSignature:output_type -> document.StampSignatureResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_document_proto_init() }
func file_proto_document_proto_init() {
	if File_proto_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_document_proto_rawDesc), len(file_proto_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_document_proto_goTypes,
		DependencyIndexes: file_proto_document_proto_depIdxs,
		MessageInfos:      file_proto_document_proto_msgTypes,
	}.Build()
	File_proto_document_proto = out.File
	file_proto_document_proto_goTypes = nil
	file_proto_document_proto_depIdxs = nil
}
