// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/document.proto

package document

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentService_ProcessPdf_FullMethodName     = "/document.DocumentService/ProcessPdf"
	DocumentService_GeneratePdf_FullMethodName    = "/document.DocumentService/GeneratePdf"
	DocumentService_GenerateDocx_FullMethodName   = "/document.DocumentService/GenerateDocx"
	DocumentService_StampSignature_FullMethodName = "/document.DocumentService/StampSignature"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DocumentService defines the RPC endpoints for PDF parsing,
// form pre-filling, signature stamping, and Word document generation.
type DocumentServiceClient interface {
	// Parses a PDF file to extract its unique ID, form field values,
	// and structural layout data (pages, coordinates, word anchors).
	ProcessPdf(ctx context.Context, in *ProcessPdfRequest, opts ...grpc.CallOption) (*ProcessPdfResponse, error)
	// Fills form values into an AcroForm PDF template.
	GeneratePdf(ctx context.Context, in *GeneratePdfRequest, opts ...grpc.CallOption) (*GeneratePdfResponse, error)
	// Generates a filled Word (DOCX) document from a template.
	GenerateDocx(ctx context.Context, in *GenerateDocxRequest, opts ...grpc.CallOption) (*GenerateDocxResponse, error)
	// Stamps a client's PNG signature image onto a PDF at the resolved coordinates.
	StampSignature(ctx context.Context, in *StampSignatureRequest, opts ...grpc.CallOption) (*StampSignatureResponse, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) ProcessPdf(ctx context.Context, in *ProcessPdfRequest, opts ...grpc.CallOption) (*ProcessPdfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessPdfResponse)
	err := c.cc.Invoke(ctx, DocumentService_ProcessPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GeneratePdf(ctx context.Context, in *GeneratePdfRequest, opts ...grpc.CallOption) (*GeneratePdfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePdfResponse)
	err := c.cc.Invoke(ctx, DocumentService_GeneratePdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GenerateDocx(ctx context.Context, in *GenerateDocxRequest, opts ...grpc.CallOption) (*GenerateDocxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDocxResponse)
	err := c.cc.Invoke(ctx, DocumentService_GenerateDocx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) StampSignature(ctx context.Context, in *StampSignatureRequest, opts ...grpc.CallOption) (*StampSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StampSignatureResponse)
	err := c.cc.Invoke(ctx, DocumentService_StampSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility.
//
// DocumentService defines the RPC endpoints for PDF parsing,
// form pre-filling, signature stamping, and Word document generation.
type DocumentServiceServer interface {
	// Parses a PDF file to extract its unique ID, form field values,
	// and structural layout data (pages, coordinates, word anchors).
	ProcessPdf(context.Context, *ProcessPdfRequest) (*ProcessPdfResponse, error)
	// Fills form values into an AcroForm PDF template.
	GeneratePdf(context.Context, *GeneratePdfRequest) (*GeneratePdfResponse, error)
	// Generates a filled Word (DOCX) document from a template.
	GenerateDocx(context.Context, *GenerateDocxRequest) (*GenerateDocxResponse, error)
	// Stamps a client's PNG signature image onto a PDF at the resolved coordinates.
	StampSignature(context.Context, *StampSignatureRequest) (*StampSignatureResponse, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServiceServer struct{}

func (UnimplementedDocumentServiceServer) ProcessPdf(context.Context, *ProcessPdfRequest) (*ProcessPdfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPdf not implemented")
}
func (UnimplementedDocumentServiceServer) GeneratePdf(context.Context, *GeneratePdfRequest) (*GeneratePdfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePdf not implemented")
}
func (UnimplementedDocumentServiceServer) GenerateDocx(context.Context, *GenerateDocxRequest) (*GenerateDocxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDocx not implemented")
}
func (UnimplementedDocumentServiceServer) StampSignature(context.Context, *StampSignatureRequest) (*StampSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StampSignature not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}
func (UnimplementedDocumentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_ProcessPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ProcessPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ProcessPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ProcessPdf(ctx, req.(*ProcessPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GeneratePdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GeneratePdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GeneratePdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GeneratePdf(ctx, req.(*GeneratePdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GenerateDocx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDocxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GenerateDocx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GenerateDocx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GenerateDocx(ctx, req.(*GenerateDocxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_StampSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StampSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).StampSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_StampSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).StampSignature(ctx, req.(*StampSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPdf",
			Handler:    _DocumentService_ProcessPdf_Handler,
		},
		{
			MethodName: "GeneratePdf",
			Handler:    _DocumentService_GeneratePdf_Handler,
		},
		{
			MethodName: "GenerateDocx",
			Handler:    _DocumentService_GenerateDocx_Handler,
		},
		{
			MethodName: "StampSignature",
			Handler:    _DocumentService_StampSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/document.proto",
}
