# ── BlueTable field schema ─────────────────────────────────────────────────
BLUETABLE_FIELDS = [
    ("Main Insured", "name"),
    ("Date of Birth", "dob"),
    ("Age", "age"),
    ("ID No./Passport No.", "id_card_no"),
    ("Nationality", "nationality"),
    ("Beneficiary Name", "beneficiary"),
    ("Relation", "bene_relation"),
    ("Occupation", "occupation"),
    ("Agent CODE/Name", "agent"),
    ("Plan", "plan"),
    ("Deductible", "deductible"),
    ("Premium", "premium"),
    ("Effective Date", "effective_date"),
    ("Personal Address", "present_address"),
    ("Tel", "tel"),
    ("Email", "email"),
    ("Payor Name", "payor_name"),
    ("Payor Address", "payor_address"),
    ("TAX ID", "tax_id"),
    ("Acceptance Conditions", "acceptance_conditions"),
    ("Exclusions", "exclusions"),
    ("Spouse Name", "sp_name"),
    ("Spouse DOB", "sp_dob"),
    ("Spouse ID", "sp_id_card_no"),
    ("Spouse Nationality", "sp_nationality"),
    ("Spouse Beneficiary", "sp_beneficiary"),
    ("Spouse Relation", "sp_bene_relation"),
    ("Spouse Occupation", "sp_occupation"),
    ("Child 1 Name", "c1_name"),
    ("Child 1 DOB", "c1_dob"),
    ("Child 1 ID", "c1_id_card_no"),
    ("Child 2 Name", "c2_name"),
    ("Child 2 DOB", "c2_dob"),
    ("Child 2 ID", "c2_id_card_no"),
    ("Child 3 Name", "c3_name"),
    ("Child 3 DOB", "c3_dob"),
    ("Child 3 ID", "c3_id_card_no"),
]
