from dataclasses import dataclass

@dataclass
class BlueTableField:
    label: str
    key: str

# ── BlueTable field schema ─────────────────────────────────────────────────
BLUETABLE_FIELDS = [
    BlueTableField("Main Insured", "name"),
    BlueTableField("Date of Birth", "dob"),
    BlueTableField("Age", "age"),
    BlueTableField("ID No./Passport No.", "id_card_no"),
    BlueTableField("Nationality", "nationality"),
    BlueTableField("Beneficiary Name", "beneficiary"),
    BlueTableField("Relation", "bene_relation"),
    BlueTableField("Occupation", "occupation"),
    BlueTableField("Agent CODE/Name", "agent"),
    BlueTableField("Plan", "plan"),
    BlueTableField("Deductible", "deductible"),
    BlueTableField("Premium", "premium"),
    BlueTableField("Effective Date", "effective_date"),
    BlueTableField("Personal Address", "present_address"),
    BlueTableField("Tel", "tel"),
    BlueTableField("Email", "email"),
    BlueTableField("Payor Name", "payor_name"),
    BlueTableField("Payor Address", "payor_address"),
    BlueTableField("TAX ID", "tax_id"),
    BlueTableField("Acceptance Conditions", "acceptance_conditions"),
    BlueTableField("Exclusions", "exclusions"),
    BlueTableField("Spouse Name", "sp_name"),
    BlueTableField("Spouse DOB", "sp_dob"),
    BlueTableField("Spouse ID", "sp_id_card_no"),
    BlueTableField("Spouse Nationality", "sp_nationality"),
    BlueTableField("Spouse Beneficiary", "sp_beneficiary"),
    BlueTableField("Spouse Relation", "sp_bene_relation"),
    BlueTableField("Spouse Occupation", "sp_occupation"),
    BlueTableField("Spouse Acceptance Conditions", "sp_acceptance_conditions"),
    BlueTableField("Spouse Exclusions", "sp_exclusions"),
    BlueTableField("Child 1 Name", "c1_name"),
    BlueTableField("Child 1 DOB", "c1_dob"),
    BlueTableField("Child 1 ID", "c1_id_card_no"),
    BlueTableField("Child 1 Nationality", "c1_nationality"),
    BlueTableField("Child 1 Beneficiary", "c1_beneficiary"),
    BlueTableField("Child 1 Relation", "c1_bene_relation"),
    BlueTableField("Child 1 Occupation", "c1_occupation"),
    BlueTableField("Child 1 Acceptance Conditions", "c1_acceptance_conditions"),
    BlueTableField("Child 1 Exclusions", "c1_exclusions"),
    BlueTableField("Child 2 Name", "c2_name"),
    BlueTableField("Child 2 DOB", "c2_dob"),
    BlueTableField("Child 2 ID", "c2_id_card_no"),
    BlueTableField("Child 2 Nationality", "c2_nationality"),
    BlueTableField("Child 2 Beneficiary", "c2_beneficiary"),
    BlueTableField("Child 2 Relation", "c2_bene_relation"),
    BlueTableField("Child 2 Occupation", "c2_occupation"),
    BlueTableField("Child 2 Acceptance Conditions", "c2_acceptance_conditions"),
    BlueTableField("Child 2 Exclusions", "c2_exclusions"),
    BlueTableField("Child 3 Name", "c3_name"),
    BlueTableField("Child 3 DOB", "c3_dob"),
    BlueTableField("Child 3 ID", "c3_id_card_no"),
    BlueTableField("Child 3 Nationality", "c3_nationality"),
    BlueTableField("Child 3 Relation", "c3_bene_relation"),
    BlueTableField("Child 3 Occupation", "c3_occupation"),
    BlueTableField("Child 3 Acceptance Conditions", "c3_acceptance_conditions"),
    BlueTableField("Child 3 Exclusions", "c3_exclusions"),
]
