# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/document.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "proto/document.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14proto/document.proto\x12\x08\x64ocument"&\n\x11ProcessPdfRequest\x12\x11\n\tpdf_bytes\x18\x01 \x01(\x0c"\xa4\x01\n\x12ProcessPdfResponse\x12\x0e\n\x06pdf_id\x18\x01 \x01(\t\x12\x38\n\x06values\x18\x02 \x03(\x0b\x32(.document.ProcessPdfResponse.ValuesEntry\x12\x15\n\rregistry_json\x18\x03 \x01(\t\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\x97\x01\n\x12GeneratePdfRequest\x12\x11\n\tpdf_bytes\x18\x01 \x01(\x0c\x12=\n\tform_data\x18\x02 \x03(\x0b\x32*.document.GeneratePdfRequest.FormDataEntry\x1a/\n\rFormDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"(\n\x13GeneratePdfResponse\x12\x11\n\tpdf_bytes\x18\x01 \x01(\x0c"\x9a\x01\n\x13GenerateDocxRequest\x12\x12\n\ndocx_bytes\x18\x01 \x01(\x0c\x12>\n\tform_data\x18\x02 \x03(\x0b\x32+.document.GenerateDocxRequest.FormDataEntry\x1a/\n\rFormDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"*\n\x14GenerateDocxResponse\x12\x12\n\ndocx_bytes\x18\x01 \x01(\x0c"\x8c\x01\n\x15StampSignatureRequest\x12\x11\n\tpdf_bytes\x18\x01 \x01(\x0c\x12\x1d\n\x15signature_image_bytes\x18\x02 \x01(\x0c\x12\x0e\n\x06pdf_id\x18\x03 \x01(\t\x12\x15\n\rregistry_json\x18\x04 \x01(\t\x12\x1a\n\x12\x63\x61\x63he_mapping_json\x18\x05 \x01(\t"+\n\x16StampSignatureResponse\x12\x11\n\tpdf_bytes\x18\x01 \x01(\x0c\x32\xca\x02\n\x0f\x44ocumentService\x12G\n\nProcessPdf\x12\x1b.document.ProcessPdfRequest\x1a\x1c.document.ProcessPdfResponse\x12J\n\x0bGeneratePdf\x12\x1c.document.GeneratePdfRequest\x1a\x1d.document.GeneratePdfResponse\x12M\n\x0cGenerateDocx\x12\x1d.document.GenerateDocxRequest\x1a\x1e.document.GenerateDocxResponse\x12S\n\x0eStampSignature\x12\x1f.document.StampSignatureRequest\x1a .document.StampSignatureResponseB!Z\x1fgateway/proto/document;documentb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.document_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\037gateway/proto/document;document"
    _globals["_PROCESSPDFRESPONSE_VALUESENTRY"]._loaded_options = None
    _globals["_PROCESSPDFRESPONSE_VALUESENTRY"]._serialized_options = b"8\001"
    _globals["_GENERATEPDFREQUEST_FORMDATAENTRY"]._loaded_options = None
    _globals["_GENERATEPDFREQUEST_FORMDATAENTRY"]._serialized_options = b"8\001"
    _globals["_GENERATEDOCXREQUEST_FORMDATAENTRY"]._loaded_options = None
    _globals["_GENERATEDOCXREQUEST_FORMDATAENTRY"]._serialized_options = b"8\001"
    _globals["_PROCESSPDFREQUEST"]._serialized_start = 34
    _globals["_PROCESSPDFREQUEST"]._serialized_end = 72
    _globals["_PROCESSPDFRESPONSE"]._serialized_start = 75
    _globals["_PROCESSPDFRESPONSE"]._serialized_end = 239
    _globals["_PROCESSPDFRESPONSE_VALUESENTRY"]._serialized_start = 194
    _globals["_PROCESSPDFRESPONSE_VALUESENTRY"]._serialized_end = 239
    _globals["_GENERATEPDFREQUEST"]._serialized_start = 242
    _globals["_GENERATEPDFREQUEST"]._serialized_end = 393
    _globals["_GENERATEPDFREQUEST_FORMDATAENTRY"]._serialized_start = 346
    _globals["_GENERATEPDFREQUEST_FORMDATAENTRY"]._serialized_end = 393
    _globals["_GENERATEPDFRESPONSE"]._serialized_start = 395
    _globals["_GENERATEPDFRESPONSE"]._serialized_end = 435
    _globals["_GENERATEDOCXREQUEST"]._serialized_start = 438
    _globals["_GENERATEDOCXREQUEST"]._serialized_end = 592
    _globals["_GENERATEDOCXREQUEST_FORMDATAENTRY"]._serialized_start = 346
    _globals["_GENERATEDOCXREQUEST_FORMDATAENTRY"]._serialized_end = 393
    _globals["_GENERATEDOCXRESPONSE"]._serialized_start = 594
    _globals["_GENERATEDOCXRESPONSE"]._serialized_end = 636
    _globals["_STAMPSIGNATUREREQUEST"]._serialized_start = 639
    _globals["_STAMPSIGNATUREREQUEST"]._serialized_end = 779
    _globals["_STAMPSIGNATURERESPONSE"]._serialized_start = 781
    _globals["_STAMPSIGNATURERESPONSE"]._serialized_end = 824
    _globals["_DOCUMENTSERVICE"]._serialized_start = 827
    _globals["_DOCUMENTSERVICE"]._serialized_end = 1157
# @@protoc_insertion_point(module_scope)
