# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import document_pb2 as proto_dot_document__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub:
    """DocumentService defines the RPC endpoints for PDF parsing,
    form pre-filling, signature stamping, and Word document generation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPdf = channel.unary_unary(
                '/document.DocumentService/ProcessPdf',
                request_serializer=proto_dot_document__pb2.ProcessPdfRequest.SerializeToString,
                response_deserializer=proto_dot_document__pb2.ProcessPdfResponse.FromString,
                _registered_method=True)
        self.GeneratePdf = channel.unary_unary(
                '/document.DocumentService/GeneratePdf',
                request_serializer=proto_dot_document__pb2.GeneratePdfRequest.SerializeToString,
                response_deserializer=proto_dot_document__pb2.GeneratePdfResponse.FromString,
                _registered_method=True)
        self.GenerateDocx = channel.unary_unary(
                '/document.DocumentService/GenerateDocx',
                request_serializer=proto_dot_document__pb2.GenerateDocxRequest.SerializeToString,
                response_deserializer=proto_dot_document__pb2.GenerateDocxResponse.FromString,
                _registered_method=True)
        self.StampSignature = channel.unary_unary(
                '/document.DocumentService/StampSignature',
                request_serializer=proto_dot_document__pb2.StampSignatureRequest.SerializeToString,
                response_deserializer=proto_dot_document__pb2.StampSignatureResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer:
    """DocumentService defines the RPC endpoints for PDF parsing,
    form pre-filling, signature stamping, and Word document generation.
    """

    def ProcessPdf(self, request, context):
        """Parses a PDF file to extract its unique ID, form field values,
        and structural layout data (pages, coordinates, word anchors).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePdf(self, request, context):
        """Fills form values into an AcroForm PDF template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDocx(self, request, context):
        """Generates a filled Word (DOCX) document from a template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StampSignature(self, request, context):
        """Stamps a client's PNG signature image onto a PDF at the resolved coordinates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPdf,
                    request_deserializer=proto_dot_document__pb2.ProcessPdfRequest.FromString,
                    response_serializer=proto_dot_document__pb2.ProcessPdfResponse.SerializeToString,
            ),
            'GeneratePdf': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePdf,
                    request_deserializer=proto_dot_document__pb2.GeneratePdfRequest.FromString,
                    response_serializer=proto_dot_document__pb2.GeneratePdfResponse.SerializeToString,
            ),
            'GenerateDocx': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDocx,
                    request_deserializer=proto_dot_document__pb2.GenerateDocxRequest.FromString,
                    response_serializer=proto_dot_document__pb2.GenerateDocxResponse.SerializeToString,
            ),
            'StampSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.StampSignature,
                    request_deserializer=proto_dot_document__pb2.StampSignatureRequest.FromString,
                    response_serializer=proto_dot_document__pb2.StampSignatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService:
    """DocumentService defines the RPC endpoints for PDF parsing,
    form pre-filling, signature stamping, and Word document generation.
    """

    @staticmethod
    def ProcessPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/ProcessPdf',
            proto_dot_document__pb2.ProcessPdfRequest.SerializeToString,
            proto_dot_document__pb2.ProcessPdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/GeneratePdf',
            proto_dot_document__pb2.GeneratePdfRequest.SerializeToString,
            proto_dot_document__pb2.GeneratePdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDocx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/GenerateDocx',
            proto_dot_document__pb2.GenerateDocxRequest.SerializeToString,
            proto_dot_document__pb2.GenerateDocxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StampSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/StampSignature',
            proto_dot_document__pb2.StampSignatureRequest.SerializeToString,
            proto_dot_document__pb2.StampSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
